"""empty message

Revision ID: bd38fd480cfb
Revises: 2ee1ccd6c343
Create Date: 2021-03-12 16:45:48.011331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd38fd480cfb'
down_revision = '2ee1ccd6c343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_img', sa.Text(), nullable=True),
    sa.Column('profile_msg', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
